[build]
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"

[build.nixpacksConfig]
providers = ["nodejs"]

# Ignore Python files for frontend build
[build.ignoreFiles]
patterns = [
  "api/*",
  "*.py", 
  "requirements.txt",
  "pyproject.toml",
  "Procfile",
  ".venv/*"
]
