version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "ai-newsletter-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=development"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
stack_name = "ai-newsletter-app"
s3_prefix = "ai-newsletter"
region = "us-east-1"
image_repositories = []

[production]
[production.global]
[production.global.parameters]
stack_name = "ai-newsletter-app-prod"
region = "us-east-1"
parameter_overrides = "Environment=production"

[production.deploy]
[production.deploy.parameters]
stack_name = "ai-newsletter-app-prod"
parameter_overrides = "Environment=production"
