service: ai-newsletter

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  api:
    handler: api/main.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

# Simple deployment without complex dependencies for now
# plugins:
#   - serverless-python-requirements

package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!.venv/**'
    - '!.aws-sam/**'
    - '!.github/**'
    - '!app/**'
    - '!components/**'
    - '!public/**'
    - '!.next/**'
    - '!*.md'
    - '!*.json'
    - '!*.js'
    - '!*.ts'
    - '!*.tsx'
    - 'api/**'
    - 'requirements.txt'
