AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AI Newsletter Generator - Serverless FastAPI Backend

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues: [development, staging, production]
  
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key for newsletter generation

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        OPENAI_API_KEY: !Ref OpenAIApiKey

Resources:
  NewsletterApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-api"
      CodeUri: api/
      Handler: main.handler
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref NewsletterApiGateway
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref NewsletterApiGateway

  NewsletterApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${NewsletterApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  ApiId:
    Description: API Gateway ID
    Value: !Ref NewsletterApiGateway
    Export:
      Name: !Sub "${AWS::StackName}-ApiId"
